#!/bin/bash

for x in 2 4 8 16 32 64 128 256
do
  echo -n -e $x "\t"
  export SSFLAGS="-ruu:size $x"
  ./run-wattch &>/tmp/stats 
  IPC=$( cat  /tmp/stats | grep sim_IPC | grep -o -E "[0-9]+\.[0-9]+" )
  Energy=$(cat /tmp/stats | grep "# total power per cycle_cc1" | grep -o -E "[0-9]+\.[0-9]+")
  echo -e $IPC'\t'$Energy


done
